### ISSUE TITLE
v2 Release

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/safe-event-emitter#5]
This issue tracks the progress of the v2 release.

Tasks:

- [x] Convert to TypeScript (#1)
- [x] Add linting (#1)
- [x] Update README with publishing instructions (#20)
- [x] Update package to be under `@metamask` scope
- [x] Switch from `npm` to `yarn` (#1)
- [ ] Benchmark vs node core (#8)
